"""migrfile

Revision ID: d516410efb33
Revises: 0a5eefee5855
Create Date: 2023-12-03 11:05:38.893599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd516410efb33'
down_revision: Union[str, None] = '0a5eefee5855'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('expire_at', postgresql.TIME(), nullable=True))
    op.add_column('files', sa.Column('one_time', sa.BOOLEAN(), nullable=False))
    op.add_column('files', sa.Column('link_code', sa.CHAR(length=255), nullable=False))
    op.create_unique_constraint(None, 'files', ['link_code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'files', type_='unique')
    op.drop_column('files', 'link_code')
    op.drop_column('files', 'one_time')
    op.drop_column('files', 'expire_at')
    # ### end Alembic commands ###
