"""migrunqfname

Revision ID: e6cd81dd8c40
Revises: 29fed2da0560
Create Date: 2023-12-17 10:21:15.603599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6cd81dd8c40'
down_revision: Union[str, None] = '29fed2da0560'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('files_filename_key', 'files', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('files_filename_key', 'files', ['filename'])
    # ### end Alembic commands ###
